# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08f8a7442c2182a3a390f753591c06f3"
name = "Greek God Saas"
application_url = "https://greek-god-saas.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders/create"

[[webhooks.subscriptions]]
topics = [ "orders/updated" ]
uri = "/webhooks/orders/updated"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_metaobjects,write_metaobjects,write_metaobject_definitions,read_orders,write_orders,read_customers,write_customers"

[auth]
redirect_urls = [ "https://greek-god-saas.vercel.app/auth/callback" ]

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"
