# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08f8a7442c2182a3a390f753591c06f3"
name = "ProfitRx RTO & Profit"
application_url = "https://greek-god-saas.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"




[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "app_subscriptions/update" ]
uri = "/webhooks/app/subscriptions/update"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders/create"

[[webhooks.subscriptions]]
topics = [ "orders/updated" ]
uri = "/webhooks/orders/updated"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,read_fulfillments,write_payment_customizations"

[auth]
redirect_urls = [
  "https://greek-god-saas.vercel.app/auth/callback",
  "https://greek-god-saas.vercel.app/auth/shopify/callback",
  "https://greek-god-saas-git-main-greek-god.vercel.app/auth/callback",
  "https://greek-god-saas-git-main-greek-god.vercel.app/auth/shopify/callback"
]

