api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "cod-blocker"
type = "function"
uid = "4c318749-0bc3-bb05-f666-2a661c1e83e30ee48e2c"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
